language: node_js

script: npm test && npm run integration-tests

after_script: .vinyldns/bin/remove-vinyl-containers.sh

node_js:
- 10.15.0

deploy:
- provider: npm
  email: vinyldns-core@googlegroups.com
  api_key:
    secure: ikENYOXvavFNVCmoilKSG8jvyOAhi6QaNoB4kGp77sQMlpDKhD/n20dIOvBzhgDeJELCzq/xis1wLuTS0+x2X80zRJhs2G3iKtc/hHB6DMO79/znkPbyO7JRjgs6m9rVDcKs6OpRGVufXxcD2ocDgewZOzo/MSf2Pdd9fYsG1fovSCMDgR4WM4sezTtfsY2d0IJjx1mZcuRLVwwk8VcnWgyoanSABgaIJCMvxaLL4Mj2W+Eclkvihl+erIvcqgcKn2lhwjk2MvNSs0DXD56AD5vXefuvfbzj6pign8CLwZYnSbfkf6lX2isQ53825FKdStZ0KpT4bKqtlufz++CiKIr8fXnizBuFb7YROQTnaP/zPcoYFrxa7XudmyoaDZsABpzOVHXvY6lEno0si4UQGjPBcBcfj5dO2o1yfATQ5029DeSWVwynhEKaiL8SNoEakAYAQAzFG2Y2cLjDizi/zusLDE3jls8Zrjq6UyrQSuIrZGzLEQA/IQYu/Aj1Q98ZxBcjrasjenA0S8FAtyTNKzz+CAc/HljR/alWaNNp/I9YPNBhYMsDQQTIacZSPz7qD27z++K7Jp4ktNBbEN6Nk9fupXIz2c3mqEAVRlLCNOmQEEjFs3VV7IPdZt8SF4CftmG7MfWBDaTDKrUmhHvTXbZ1MjhLhgYRnPrLlKQy4qE
  on:
    tags: true
    repo: vinyldns/vinyldns-js
- provider: pages
  skip-cleanup: true
  local-dir: docs
  github-token:
    secure: t4tJBzoF6FpIEKXkJqIhLEcyov0hD2t901rrlcdIUCQY32MBmXsrnGmc4d3fxXQS2nByg/IYIrfzLFhJbju7C6XaXcyVA29BTkhu1qFnXexxsMSida+KPxqbQQCI/rTca0tkjRmcgDpGYKk/5o97DrUVUgEZRrohqn4a48IAeedYSofYBG4+N/Ps7l0Y9A0u5BunXbAb3xWffRvpPlx2ujIKP28o7c/6a0v0wPzQH812LSxepnRqQm73jtxftcILcSsF5KLI+wn6aJTW4NM4RxstbXq5yF845fK3GW85RMWXG+okZqqIZhAfE//hvBJpC8Ig+VtaBRw6RPaZ0JkcqHDa/eZZgmzyHXucm+ERLSB46RS4Ol5fRaozxv78uxwRK/VT0SHofaw0VaKeTQ5sa0wItQd6PX5PUpOoUYLIpHuf5PdqUeLAZ95AJbAVZxklsvDoLmquPrzBCAKBSMT7aADjw6XU+jjoY4ik0JdGuNfUJWqbuT8UdKdouAXQmoI+8MduO65OvtPaGad5RRtJQ5t/6HsM90lAtWV+Y9EleOhkJi46i+bi5JuZwneoMiEtUjhu/y4lb4i3LCtUEv/SJdNC1PScnz9R727zjNfKgvFy5/JM6jCVPxZtt62DI2Bn0ZDffG2yqXsgM2nv2KbNl8qOyuEtTXJYGhaebfR9UEU=
  on:
    tags: true
    repo: vinyldns/vinyldns-js

notifications:
  email:
    on_success: change
    on_failure: change
