name: verify

on:
  pull_request:
    branches: [ '*' ]
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Run unit-tests
        run: npm test
        shell: bash

      - name: Run integration-tests
        run: npm run integration-tests
        shell: bash